spring.application.name=workout-tracker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/workoutdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:workout_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:strongpassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:mysecretkey123mysecretkey123mysecretkey123}
jwt.expiration=${JWT_EXPIRATION:36000000}

